import React from 'react';
import { FileDown } from 'lucide-react';

export function PDFExport({ cycles, symptoms, stats, riskAssessment }) {
  const generatePDF = () => {
    // Create a comprehensive health report
    const reportContent = `
AURA HEALTH REPORT
Generated: ${new Date().toLocaleDateString()}

===========================================
CYCLE STATISTICS
===========================================

Total Cycles Tracked: ${stats?.total_cycles || 0}
Average Cycle Length: ${stats?.average_cycle_length || 'N/A'} days
Cycle Regularity: ${stats?.is_irregular ? 'Irregular' : 'Regular'}
Irregularity Score: ${stats?.irregularity_score || 0}

===========================================
CYCLE HISTORY
===========================================

${cycles && cycles.length > 0 ? cycles.map((cycle, i) => `
Cycle ${i + 1}:
  Start Date: ${new Date(cycle.start_date).toLocaleDateString()}
  End Date: ${cycle.end_date ? new Date(cycle.end_date).toLocaleDateString() : 'Ongoing'}
  Flow Intensity: ${cycle.flow_intensity}
`).join('\n') : 'No cycles recorded'}

===========================================
SYMPTOM SUMMARY
===========================================

Total Symptom Entries: ${symptoms?.length || 0}

${symptoms && symptoms.length > 0 ? symptoms.slice(0, 10).map((symptom, i) => `
Entry ${i + 1} (${new Date(symptom.date).toLocaleDateString()}):
  Mood: ${symptom.mood || 'Not recorded'}
  Pain Level: ${symptom.pain_level || 0}/10
  Fatigue: ${symptom.fatigue || 0}/10
  Symptoms: ${[
    symptom.cramps && 'Cramps',
    symptom.headache && 'Headache',
    symptom.acne && 'Acne',
    symptom.bloating && 'Bloating'
  ].filter(Boolean).join(', ') || 'None'}
  Notes: ${symptom.notes || 'None'}
`).join('\n') : 'No symptoms recorded'}

===========================================
PCOD RISK ASSESSMENT
===========================================

Risk Level: ${riskAssessment?.risk_level || 'Not assessed'}
Probability: ${riskAssessment ? Math.round(riskAssessment.probability * 100) : 0}%

${riskAssessment?.recommendations ? `
Recommendations:
${riskAssessment.recommendations.map((rec, i) => `
${i + 1}. [${rec.priority.toUpperCase()}] ${rec.category}
   ${rec.text}
`).join('\n')}` : ''}

===========================================
DISCLAIMER
===========================================

This report is for informational purposes only and does not 
constitute medical advice. Please consult with a qualified 
healthcare professional for proper medical evaluation and 
treatment recommendations.

===========================================
Generated by Aura - Smart Period Tracking
===========================================
    `.trim();

    // Create a blob and download
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `aura-health-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="pdf-export-card">
      <div className="pdf-export-header">
        <FileDown size={24} />
        <div>
          <h3>Export Health Report</h3>
          <p className="pdf-export-subtitle">Download your complete health data</p>
        </div>
      </div>
      <button onClick={generatePDF} className="btn-export">
        <FileDown size={20} />
        Download Report
      </button>
      <p className="pdf-export-note">
        Includes cycle history, symptoms, and PCOD risk assessment
      </p>
    </div>
  );
}
